package com.calimero.mero.invite

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The invitation wire format, and its compatibility with the JavaScript apps.
 *
 * The fixture below was generated by the real JS libraries (`bs58` +
 * `fflate.deflateSync`, level 9) that every web and desktop Calimero app uses.
 * If a change here stops decoding it, invitations sent from a web app stop
 * working on Android — a silent, user-visible break — so it is pinned.
 */
class InviteCodecTest {
    /** base58(deflate(JSON)) produced by bs58 + fflate. */
    private val jsToken = "T3MBR42kMWfzJn5wMvCqe1r7c1hYDuexnUKzqjSNCtW4k71PM1Jkbton9UzSky4P3Vu2kz8bft3hcchY2HESbzeq4WbgLAjTJs6Ep9vxyp5hCD3s9geS6EjLnBnDAQ5Lr2CjSQxB5h7vQmGu11ARv7ty7YAtw"
    private val jsJson = """{"__teamName":"Design Team","invitation":{"invitation":{"expires_at":1787740000000,"group_id":[13,20,27,34,41,48]},"inviter_signature":"5555"}}"""

    @Test
    fun `decodes a token produced by the javascript apps`() {
        assertEquals(jsJson, InviteCodec.decode(jsToken))
    }

    @Test
    fun `our own token decodes back to the same json`() {
        // Our compressor and fflate do not emit identical bytes for the same
        // input, so the tokens differ. What must hold is that each side inflates
        // the other's output.
        assertEquals(jsJson, InviteCodec.decode(InviteCodec.encode(jsJson)))
    }

    @Test
    fun `round trips non ascii text`() {
        val json = """{"__teamName":"Café — 東京 🎨"}"""
        assertEquals(json, InviteCodec.decode(InviteCodec.encode(json)))
    }

    @Test
    fun `compression is worth it`() {
        val json = jsJson.repeat(3)
        assertTrue(InviteCodec.encode(json).length < json.length)
    }

    @Test
    fun `decodes the legacy base64url form`() {
        val json = """{"invitation":{"group_id":"abc"}}"""
        val encoder = java.util.Base64.getUrlEncoder().withoutPadding()
        val b64 = encoder.encodeToString(json.toByteArray(Charsets.UTF_8))
        assertEquals(json, InviteCodec.decode(b64))
    }

    @Test
    fun `decodes uncompressed base58`() {
        val json = """{"invitation":{"group_id":"abc"}}"""
        val token = InviteCodec.base58Encode(json.toByteArray(Charsets.UTF_8))
        assertEquals(json, InviteCodec.decode(token))
    }

    @Test
    fun `decodes raw json`() {
        assertEquals("""{"a":1}""", InviteCodec.decode("""{"a":1}"""))
    }

    @Test
    fun `rejects a short ambiguous string rather than returning mojibake`() {
        // "YQ" is valid base58 AND valid base64url; neither reading is JSON.
        assertNull(InviteCodec.decode("YQ"))
        assertNull(InviteCodec.decode("YWI"))
        assertNull(InviteCodec.decode("not an invitation"))
        assertNull(InviteCodec.decode("   "))
    }

    @Test
    fun `base58 rejects characters outside the alphabet`() {
        // 0, O, I and l are deliberately absent from base58.
        assertNull(InviteCodec.base58Decode("0OIl"))
    }

    @Test
    fun `base58 preserves leading zero bytes`() {
        val data = byteArrayOf(0, 0, 1, 2, 3)
        val encoded = InviteCodec.base58Encode(data)
        assertTrue(encoded.startsWith("11"))
        assertTrue(data.contentEquals(InviteCodec.base58Decode(encoded)))
    }

    @Test
    fun `inflate returns null on garbage rather than looping`() {
        assertNull(InviteCodec.inflate(byteArrayOf(1, 2, 3, 4, 5)))
    }
}
