package com.calimero.mero.invite

import java.io.ByteArrayOutputStream
import java.util.zip.Deflater
import java.util.zip.Inflater

/**
 * Turning a signed invitation into something a person can send, and back.
 *
 * [com.calimero.mero.admin.AdminApi] already mints invitations
 * (`createNamespaceInvitation`) and redeems them (`joinNamespace`). What was
 * missing is the bit in between: the wire format the rest of the fleet shares,
 * so an invitation created on a phone can be redeemed by the desktop or the web
 * build, and vice versa.
 *
 * The format is `base58(deflate(JSON))` — what mero-blocks, merraria,
 * mero-stream, mero-chat and the web apps all emit. Compression is not
 * cosmetic: the payload is JSON carrying 32-byte arrays rendered as decimal
 * numbers, so it is enormously redundant. A real invitation is a ~930-character
 * link as plain base64url and ~540 this way.
 *
 * **On the deflate flavour.** [Deflater] with `nowrap = true` produces *raw*
 * DEFLATE (RFC 1951) with no zlib header, which is what the JS side's
 * `fflate.deflateSync` produces and what Apple's
 * `NSData.compressed(using: .zlib)` produces on iOS. The compressors do not emit
 * identical bytes for the same input and do not need to — each inflates the
 * others' output. [InviteCodecTest] pins a token generated by the real JS
 * libraries, so a regression here fails CI instead of silently breaking
 * invitations sent from the web.
 *
 * Everything here is pure and JVM-only (no `android.util.*`), so it is unit
 * testable without a device.
 */
object InviteCodec {
    private const val ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
    private val INDEX: Map<Char, Int> = ALPHABET.withIndex().associate { (i, c) -> c to i }

    /** Base58 (bitcoin alphabet), byte-compatible with the JS `bs58` package. */
    fun base58Encode(data: ByteArray): String {
        if (data.isEmpty()) return ""
        val digits = ArrayList<Int>(data.size * 2)
        digits.add(0)
        for (byte in data) {
            var carry = byte.toInt() and 0xff
            for (i in digits.indices) {
                carry += digits[i] shl 8
                digits[i] = carry % 58
                carry /= 58
            }
            while (carry > 0) {
                digits.add(carry % 58)
                carry /= 58
            }
        }
        val out = StringBuilder()
        // Leading zero bytes encode as leading '1's, not as digits.
        for (byte in data) {
            if (byte.toInt() == 0) out.append(ALPHABET[0]) else break
        }
        for (i in digits.indices.reversed()) out.append(ALPHABET[digits[i]])
        return out.toString()
    }

    /** Returns null for any character outside the base58 alphabet. */
    fun base58Decode(value: String): ByteArray? {
        if (value.isEmpty()) return ByteArray(0)
        val bytes = ArrayList<Int>(value.length)
        bytes.add(0)
        for (ch in value) {
            var carry = INDEX[ch] ?: return null
            for (i in bytes.indices) {
                carry += bytes[i] * 58
                bytes[i] = carry and 0xff
                carry = carry shr 8
            }
            while (carry > 0) {
                bytes.add(carry and 0xff)
                carry = carry shr 8
            }
        }
        var leadingZeros = 0
        for (ch in value) {
            if (ch == ALPHABET[0]) leadingZeros++ else break
        }
        val out = ByteArray(leadingZeros + bytes.size)
        for (i in bytes.indices) out[leadingZeros + i] = bytes[bytes.size - 1 - i].toByte()
        return out
    }

    /** Raw DEFLATE, matching JS `fflate.deflateSync` and Swift `.zlib`. */
    internal fun deflate(data: ByteArray): ByteArray {
        val deflater = Deflater(Deflater.BEST_COMPRESSION, true)
        try {
            deflater.setInput(data)
            deflater.finish()
            val out = ByteArrayOutputStream(data.size)
            val buffer = ByteArray(4096)
            while (!deflater.finished()) {
                val n = deflater.deflate(buffer)
                out.write(buffer, 0, n)
            }
            return out.toByteArray()
        } finally {
            deflater.end()
        }
    }

    /** Raw INFLATE. Returns null when [data] is not a valid raw DEFLATE stream. */
    internal fun inflate(data: ByteArray): ByteArray? {
        val inflater = Inflater(true)
        try {
            inflater.setInput(data)
            val out = ByteArrayOutputStream(data.size * 4)
            val buffer = ByteArray(4096)
            while (!inflater.finished()) {
                val n =
                    try {
                        inflater.inflate(buffer)
                    } catch (_: java.util.zip.DataFormatException) {
                        return null
                    }
                // A zero-length read with nothing left to consume means the
                // stream is truncated rather than finished; bail instead of
                // spinning forever.
                if (n == 0 && (inflater.needsInput() || inflater.needsDictionary())) return null
                out.write(buffer, 0, n)
            }
            return out.toByteArray()
        } finally {
            inflater.end()
        }
    }

    /** Compress and base58-encode a JSON string into the shareable token. */
    fun encode(json: String): String = base58Encode(deflate(json.toByteArray(Charsets.UTF_8)))

    /**
     * Decode any form the fleet has ever emitted, back to the JSON string:
     *
     * 1. `base58(deflate(JSON))` — what [encode] produces
     * 2. `base58(JSON)` — uncompressed, from older clients
     * 3. `base64url(JSON)` — what several web apps emitted before compressing
     * 4. raw JSON — hand-assembled, and useful when debugging
     *
     * base58 is attempted first because the two alphabets overlap: a short
     * string can be valid in both and only one reading is right. Every branch
     * additionally requires the result to *look* like JSON before accepting it —
     * without that, a short base58 string decodes to arbitrary bytes and the
     * caller gets mojibake instead of a clear failure.
     *
     * Returns null when nothing decodes, so a malformed invitation fails loudly.
     */
    fun decode(token: String): String? {
        val trimmed = token.trim()
        if (trimmed.isEmpty()) return null
        return firstDecodable(trimmed)
    }

    /**
     * The forms above, tried in order, as a single expression — one exit point,
     * so the sequence stays readable and detekt's return-count limit is not the
     * thing shaping the code.
     */
    private fun firstDecodable(trimmed: String): String? {
        if (looksLikeJson(trimmed)) return trimmed

        val base58 = base58Decode(trimmed)
        val compressed = base58?.let { inflate(it) }?.let { asJson(it) }
        val uncompressed = base58?.let { asJson(it) }
        val legacyBase64 = base64UrlDecode(trimmed)?.let { asJson(it) }

        return compressed ?: uncompressed ?: legacyBase64
    }

    private fun looksLikeJson(s: String): Boolean = s.trimStart().startsWith("{")

    private fun asJson(bytes: ByteArray): String? {
        val text =
            try {
                bytes.toString(Charsets.UTF_8)
            } catch (_: Exception) {
                return null
            }
        return if (looksLikeJson(text)) text else null
    }

    /**
     * Hand-rolled rather than `java.util.Base64`, which is API 26+ — this has to
     * work on the minSdk the SDK supports, same reasoning as `Jwt.kt`.
     */
    private fun base64UrlDecode(value: String): ByteArray? {
        val chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
        val normalized = value.replace('-', '+').replace('_', '/')
        var buffer = 0
        var bits = 0
        val out = ByteArrayOutputStream(normalized.length * 3 / 4 + 3)
        for (ch in normalized) {
            if (ch == '=') break
            val index = chars.indexOf(ch)
            if (index < 0) return null
            buffer = (buffer shl 6) or index
            bits += 6
            if (bits >= 8) {
                bits -= 8
                out.write((buffer shr bits) and 0xff)
            }
        }
        return out.toByteArray()
    }
}
